<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW7gNXZ3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW7gNXZ3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW7gNXZ3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW7gNXZ3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW7gNXZ3\App_KernelDevDebugContainer([
    'container.build_hash' => 'W7gNXZ3',
    'container.build_id' => '2978c804',
    'container.build_time' => 1633522132,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW7gNXZ3');
